run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - nolintlint

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  goimports:
    local-prefixes: github.com/truvity/zitadel-operator
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unparam
