{{- if and .Values.rbac.create (not .Values.rbac.namespaces) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zitadel-operator.fullname" . }}
  labels:
    {{- include "zitadel-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - zitadel.truvity.io
    resources:
      - actionexecutions
      - actiontargets
      - apiapps
      - applicationkeys
      - defaultdomainpolicies
      - defaultlabelpolicies
      - defaultlockoutpolicies
      - defaultloginpolicies
      - defaultmessagetexts
      - defaultnotificationpolicies
      - defaultoidcsettings
      - defaultpasswordagepolicies
      - defaultpasswordcomplexitypolicies
      - defaultprivacypolicies
      - domains
      - emailproviders
      - githubidps
      - googleidps
      - humanusers
      - identityproviders
      - instancemembers
      - labelpolicies
      - lockoutpolicies
      - loginpolicies
      - machineusers
      - messagetexts
      - notificationpolicies
      - oidcapps
      - organizations
      - orgmembers
      - orgmetadata
      - passwordagepolicies
      - passwordcomplexitypolicies
      - personalaccesstokens
      - privacypolicies
      - projectgrantmembers
      - projectgrants
      - projectmembers
      - projects
      - samlapps
      - smsproviders
      - usergrants
      - zitadelscopemaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - zitadel.truvity.io
    resources:
      - actionexecutions/status
      - actiontargets/status
      - apiapps/status
      - applicationkeys/status
      - defaultdomainpolicies/status
      - defaultlabelpolicies/status
      - defaultloginpolicies/status
      - defaultlockoutpolicies/status
      - defaultmessagetexts/status
      - defaultnotificationpolicies/status
      - defaultoidcsettings/status
      - defaultpasswordagepolicies/status
      - defaultpasswordcomplexitypolicies/status
      - defaultprivacypolicies/status
      - domains/status
      - emailproviders/status
      - githubidps/status
      - googleidps/status
      - humanusers/status
      - identityproviders/status
      - instancemembers/status
      - labelpolicies/status
      - lockoutpolicies/status
      - loginpolicies/status
      - machineusers/status
      - messagetexts/status
      - notificationpolicies/status
      - oidcapps/status
      - organizations/status
      - orgmembers/status
      - orgmetadata/status
      - passwordagepolicies/status
      - passwordcomplexitypolicies/status
      - personalaccesstokens/status
      - privacypolicies/status
      - projectgrantmembers/status
      - projectgrants/status
      - projectmembers/status
      - projects/status
      - samlapps/status
      - smsproviders/status
      - usergrants/status
      - zitadelscopemaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - zitadel.truvity.io
    resources:
      - actionexecutions/finalizers
      - actiontargets/finalizers
      - apiapps/finalizers
      - applicationkeys/finalizers
      - defaultdomainpolicies/finalizers
      - defaultlabelpolicies/finalizers
      - defaultloginpolicies/finalizers
      - defaultlockoutpolicies/finalizers
      - defaultmessagetexts/finalizers
      - defaultnotificationpolicies/finalizers
      - defaultoidcsettings/finalizers
      - defaultpasswordagepolicies/finalizers
      - defaultpasswordcomplexitypolicies/finalizers
      - defaultprivacypolicies/finalizers
      - domains/finalizers
      - emailproviders/finalizers
      - githubidps/finalizers
      - googleidps/finalizers
      - humanusers/finalizers
      - identityproviders/finalizers
      - instancemembers/finalizers
      - labelpolicies/finalizers
      - lockoutpolicies/finalizers
      - loginpolicies/finalizers
      - machineusers/finalizers
      - messagetexts/finalizers
      - notificationpolicies/finalizers
      - oidcapps/finalizers
      - organizations/finalizers
      - orgmembers/finalizers
      - orgmetadata/finalizers
      - passwordagepolicies/finalizers
      - passwordcomplexitypolicies/finalizers
      - personalaccesstokens/finalizers
      - privacypolicies/finalizers
      - projectgrantmembers/finalizers
      - projectgrants/finalizers
      - projectmembers/finalizers
      - projects/finalizers
      - samlapps/finalizers
      - smsproviders/finalizers
      - usergrants/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
{{- end }}
