{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zitadel-operator.fullname" . }}
  labels:
    {{- include "zitadel-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - zitadel.truvity.io
    resources:
      - applicationkeys
      - identityproviders
      - lockoutpolicies
      - loginpolicies
      - machineusers
      - oidcapps
      - organizations
      - passwordcomplexitypolicies
      - personalaccesstokens
      - projectgrants
      - projectmembers
      - projects
      - usergrants
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - zitadel.truvity.io
    resources:
      - applicationkeys/status
      - identityproviders/status
      - lockoutpolicies/status
      - loginpolicies/status
      - machineusers/status
      - oidcapps/status
      - organizations/status
      - passwordcomplexitypolicies/status
      - personalaccesstokens/status
      - projectgrants/status
      - projectmembers/status
      - projects/status
      - usergrants/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - zitadel.truvity.io
    resources:
      - applicationkeys/finalizers
      - identityproviders/finalizers
      - lockoutpolicies/finalizers
      - loginpolicies/finalizers
      - machineusers/finalizers
      - oidcapps/finalizers
      - organizations/finalizers
      - passwordcomplexitypolicies/finalizers
      - personalaccesstokens/finalizers
      - projectgrants/finalizers
      - projectmembers/finalizers
      - projects/finalizers
      - usergrants/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
{{- end }}
