{{- if and .Values.rbac.create .Values.rbac.namespaces -}}
{{- range .Values.rbac.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "zitadel-operator.fullname" $ }}
  namespace: {{ . }}
  labels:
    {{- include "zitadel-operator.labels" $ | nindent 4 }}
rules:
  - apiGroups:
      - zitadel.truvity.io
    resources:
      - machineusers
      - oidcapps
      - organizations
      - projects
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - zitadel.truvity.io
    resources:
      - machineusers/status
      - oidcapps/status
      - organizations/status
      - projects/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - zitadel.truvity.io
    resources:
      - machineusers/finalizers
      - oidcapps/finalizers
      - organizations/finalizers
      - projects/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
{{- end }}
{{- end }}
