---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zitadel-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zitadel.truvity.io
  resources:
  - actionexecutions
  - actiontargets
  - apiapps
  - applicationkeys
  - domains
  - identityproviders
  - machineusers
  - oidcapps
  - organizations
  - orgmetadata
  - personalaccesstokens
  - projectgrantmembers
  - projectgrants
  - projectmembers
  - projectroles
  - projects
  - samlapps
  - usergrants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zitadel.truvity.io
  resources:
  - actionexecutions/finalizers
  - actiontargets/finalizers
  - apiapps/finalizers
  - applicationkeys/finalizers
  - domains/finalizers
  - identityproviders/finalizers
  - machineusers/finalizers
  - oidcapps/finalizers
  - organizations/finalizers
  - orgmetadata/finalizers
  - personalaccesstokens/finalizers
  - projectgrantmembers/finalizers
  - projectgrants/finalizers
  - projectmembers/finalizers
  - projectroles/finalizers
  - projects/finalizers
  - samlapps/finalizers
  - usergrants/finalizers
  verbs:
  - update
- apiGroups:
  - zitadel.truvity.io
  resources:
  - actionexecutions/status
  - actiontargets/status
  - apiapps/status
  - applicationkeys/status
  - domains/status
  - identityproviders/status
  - machineusers/status
  - oidcapps/status
  - organizations/status
  - orgmetadata/status
  - personalaccesstokens/status
  - projectgrantmembers/status
  - projectgrants/status
  - projectmembers/status
  - projectroles/status
  - projects/status
  - samlapps/status
  - usergrants/status
  verbs:
  - get
  - patch
  - update
