name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: true

      - name: Run all checks
        run: devbox run just check
