name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - uses: jetify-com/devbox-install-action@a0d2d53632934ae004f878c840055956d9f741b0 # v0.14.0
        with:
          enable-cache: true
          skip-nix-installation: true

      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: GoReleaser
        run: devbox run -- goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KO_DOCKER_REPO: ghcr.io/truvity/zitadel-operator

      - name: Package and push Helm charts
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "${{ secrets.GITHUB_TOKEN }}" | devbox run -- helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
          devbox run -- helm package charts/zitadel-operator --version "$VERSION" --app-version "$VERSION" --destination dist/
          devbox run -- helm package charts/zitadel-operator-crds --version "$VERSION" --app-version "$VERSION" --destination dist/
          devbox run -- helm push dist/zitadel-operator-${VERSION}.tgz oci://ghcr.io/truvity/charts
          devbox run -- helm push dist/zitadel-operator-crds-${VERSION}.tgz oci://ghcr.io/truvity/charts
